### ISSUE TITLE
Is it workable?

### ISSUE THREAD

**Issue by kamranhossain** [EugeneBad/DjangoChannels-Angular-Docker#2]
Is this workable? Can you share how urls work?

**Comment by EugeneBad** [comment]
@kamranhossain if you are refering to the application as a whole then yes it is fully workable; when setup correctly, it's accessed only through the root url (http://localhost).
It also uses angular routes to switch between `/auth` and `/dashboard` depending on whether the user is logged in.
As for the websocket endpoints, they are well defined in `/backend/djchannels/routing.py` in typical channels style.
PS: Sorry for late response :)

**Comment by kamranhossain** [comment]
No problem. A few days ago I need to integrate Django Channel with Angular. But it was passed for few reasons. I let you know if something I need to explore about this repo. Thanks. :)
